/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UnderwriteManagerInterface extends ethers.utils.Interface {
  functions: {
    "CREDIT_RENEWAL()": FunctionFragment;
    "LEVERAGE_DENOMINATOR()": FunctionFragment;
    "MINIMUM_COLLATERAL()": FunctionFragment;
    "MU_PRICE_DENOMINATOR_USD()": FunctionFragment;
    "MWEI()": FunctionFragment;
    "REWARD_PERCENT()": FunctionFragment;
    "calculateCredit(uint256)": FunctionFragment;
    "claimReward()": FunctionFragment;
    "collateralToken()": FunctionFragment;
    "creditLines(address,address)": FunctionFragment;
    "getCreditLines(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "isActive()": FunctionFragment;
    "owner()": FunctionFragment;
    "renewCreditLine(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewards(address)": FunctionFragment;
    "toggleActive()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "underwrite(address,uint256,address)": FunctionFragment;
    "underwritees(address)": FunctionFragment;
    "updateReward(address,uint256)": FunctionFragment;
    "withdraw(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CREDIT_RENEWAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEVERAGE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MU_PRICE_DENOMINATOR_USD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MWEI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REWARD_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCredit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditLines",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditLines",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renewCreditLine",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rewards", values: [string]): string;
  encodeFunctionData(
    functionFragment: "toggleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underwrite",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "underwritees",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReward",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "CREDIT_RENEWAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEVERAGE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MU_PRICE_DENOMINATOR_USD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MWEI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditLines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditLines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "underwrite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "underwritees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "RewardClaimed(address,uint256)": EventFragment;
    "RewardUpdated(address,uint256)": EventFragment;
    "Underwrite(address,tuple)": EventFragment;
    "Withdrawl(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Underwrite"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawl"): EventFragment;
}

export class UnderwriteManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UnderwriteManagerInterface;

  functions: {
    CREDIT_RENEWAL(overrides?: CallOverrides): Promise<[BigNumber]>;

    LEVERAGE_DENOMINATOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINIMUM_COLLATERAL(overrides?: CallOverrides): Promise<[BigNumber]>;

    MU_PRICE_DENOMINATOR_USD(overrides?: CallOverrides): Promise<[BigNumber]>;

    MWEI(overrides?: CallOverrides): Promise<[BigNumber]>;

    REWARD_PERCENT(overrides?: CallOverrides): Promise<[BigNumber]>;

    calculateCredit(
      collateralAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    collateralToken(overrides?: CallOverrides): Promise<[string]>;

    creditLines(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        collateral: BigNumber;
        networkToken: string;
        issueDate: BigNumber;
      }
    >;

    getCreditLines(
      underwriter: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, string, BigNumber] & {
          collateral: BigNumber;
          networkToken: string;
          issueDate: BigNumber;
        })[]
      ]
    >;

    initialize(
      _collateralTokenAddress: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isActive(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renewCreditLine(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewards(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    toggleActive(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    underwrite(
      networkToken: string,
      collateralAmount: BigNumberish,
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    underwritees(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    updateReward(
      underwritee: string,
      txAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CREDIT_RENEWAL(overrides?: CallOverrides): Promise<BigNumber>;

  LEVERAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

  MINIMUM_COLLATERAL(overrides?: CallOverrides): Promise<BigNumber>;

  MU_PRICE_DENOMINATOR_USD(overrides?: CallOverrides): Promise<BigNumber>;

  MWEI(overrides?: CallOverrides): Promise<BigNumber>;

  REWARD_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  calculateCredit(
    collateralAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimReward(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  collateralToken(overrides?: CallOverrides): Promise<string>;

  creditLines(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      collateral: BigNumber;
      networkToken: string;
      issueDate: BigNumber;
    }
  >;

  getCreditLines(
    underwriter: string,
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, string, BigNumber] & {
      collateral: BigNumber;
      networkToken: string;
      issueDate: BigNumber;
    })[]
  >;

  initialize(
    _collateralTokenAddress: string,
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isActive(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renewCreditLine(
    underwritee: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  toggleActive(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  underwrite(
    networkToken: string,
    collateralAmount: BigNumberish,
    underwritee: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  underwritees(arg0: string, overrides?: CallOverrides): Promise<string>;

  updateReward(
    underwritee: string,
    txAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    underwritee: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CREDIT_RENEWAL(overrides?: CallOverrides): Promise<BigNumber>;

    LEVERAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_COLLATERAL(overrides?: CallOverrides): Promise<BigNumber>;

    MU_PRICE_DENOMINATOR_USD(overrides?: CallOverrides): Promise<BigNumber>;

    MWEI(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    calculateCredit(
      collateralAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimReward(overrides?: CallOverrides): Promise<void>;

    collateralToken(overrides?: CallOverrides): Promise<string>;

    creditLines(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        collateral: BigNumber;
        networkToken: string;
        issueDate: BigNumber;
      }
    >;

    getCreditLines(
      underwriter: string,
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, string, BigNumber] & {
        collateral: BigNumber;
        networkToken: string;
        issueDate: BigNumber;
      })[]
    >;

    initialize(
      _collateralTokenAddress: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isActive(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renewCreditLine(
      underwritee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    toggleActive(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    underwrite(
      networkToken: string,
      collateralAmount: BigNumberish,
      underwritee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    underwritees(arg0: string, overrides?: CallOverrides): Promise<string>;

    updateReward(
      underwritee: string,
      txAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(underwritee: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    RewardClaimed(
      underwriter?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { underwriter: string; amount: BigNumber }
    >;

    RewardUpdated(
      underwriter?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { underwriter: string; amount: BigNumber }
    >;

    Underwrite(
      underwriter?: null,
      creditLine?: null
    ): TypedEventFilter<
      [
        string,
        [BigNumber, string, BigNumber] & {
          collateral: BigNumber;
          networkToken: string;
          issueDate: BigNumber;
        }
      ],
      {
        underwriter: string;
        creditLine: [BigNumber, string, BigNumber] & {
          collateral: BigNumber;
          networkToken: string;
          issueDate: BigNumber;
        };
      }
    >;

    Withdrawl(
      underwriter?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { underwriter: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    CREDIT_RENEWAL(overrides?: CallOverrides): Promise<BigNumber>;

    LEVERAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_COLLATERAL(overrides?: CallOverrides): Promise<BigNumber>;

    MU_PRICE_DENOMINATOR_USD(overrides?: CallOverrides): Promise<BigNumber>;

    MWEI(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    calculateCredit(
      collateralAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    collateralToken(overrides?: CallOverrides): Promise<BigNumber>;

    creditLines(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreditLines(
      underwriter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _collateralTokenAddress: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isActive(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renewCreditLine(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    toggleActive(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    underwrite(
      networkToken: string,
      collateralAmount: BigNumberish,
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    underwritees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateReward(
      underwritee: string,
      txAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CREDIT_RENEWAL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LEVERAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MINIMUM_COLLATERAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MU_PRICE_DENOMINATOR_USD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MWEI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REWARD_PERCENT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateCredit(
      collateralAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimReward(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    collateralToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creditLines(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreditLines(
      underwriter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _collateralTokenAddress: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renewCreditLine(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toggleActive(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    underwrite(
      networkToken: string,
      collateralAmount: BigNumberish,
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    underwritees(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateReward(
      underwritee: string,
      txAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      underwritee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
